import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fontsRoot = path.join(root, "src", "HealthIcons.Maui", "Resources", "Fonts");
const srcRoot = path.join(root, "src", "HealthIcons.Maui");

function pascalCase(input) {
  const cleaned = input.replace(/[^a-zA-Z0-9]+/g, " ");
  const joined = cleaned
    .split(" ")
    .filter(Boolean)
    .map(part => part[0].toUpperCase() + part.slice(1))
    .join("");

  return /^\d/.test(joined) ? `Icon${joined}` : joined;
}

function sanitizeIdentifier(name, seen) {
  let candidate = pascalCase(name);
  if (!candidate) {
    candidate = "Icon";
  }

  if (seen.has(candidate)) {
    let suffix = 2;
    while (seen.has(`${candidate}${suffix}`)) {
      suffix++;
    }

    candidate = `${candidate}${suffix}`;
  }

  seen.add(candidate);
  return candidate;
}

async function generateClass(jsonName, className, outputFile) {
  const raw = await fs.readFile(path.join(fontsRoot, jsonName), "utf8");
  const map = JSON.parse(raw);
  const entries = Object.entries(map).sort(([a], [b]) => a.localeCompare(b));
  const seen = new Set();
  const lines = [
    "namespace HealthIcons.Maui;",
    "",
    "// Generated by tools/generate-csharp.mjs",
    `public static class ${className}`,
    "{"
  ];

  for (const [name, codepoint] of entries) {
    const propertyName = sanitizeIdentifier(name, seen);
    const numericCodepoint = Number(codepoint);
    const value = numericCodepoint.toString(16).toUpperCase().padStart(4, "0");
    const glyph = numericCodepoint <= 0xFFFF
      ? `\\u${value}`
      : `\\U${numericCodepoint.toString(16).toUpperCase().padStart(8, "0")}`;
    lines.push(`    public const string ${propertyName} = \"${glyph}\";`);
  }

  lines.push("}");
  lines.push("");
  await fs.writeFile(path.join(srcRoot, outputFile), lines.join("\n"), "utf8");
}

await generateClass("HealthIcons-Filled.json", "Filled", "HealthIcons.Filled.cs");
await generateClass("HealthIcons-Outline.json", "Outline", "HealthIcons.Outline.cs");

